server:
  port: 8081
  
spring:
  application:
    name: "notifications"
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5435/notificationsDbP
    username: admin

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest		
